#ifndef ASSIGNMENTCREATIONWINDOWADDHEADERCOMMAND_H
#define ASSIGNMENTCREATIONWINDOWADDHEADERCOMMAND_H


class AssignmentCreationWindowAddHeaderCommand
{
public:
    AssignmentCreationWindowAddHeaderCommand();
};

#endif // ASSIGNMENTCREATIONWINDOWADDHEADERCOMMAND_H
